# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

variables:
  scheme: ''
  sdk: 'iphoneos'
  configuration: 'Release'

pool:
  vmImage: 'macos-latest'

steps:
- script: /usr/local/bin/pod install
  displayName: 'pod install using a script'

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'certDA.p12'
    certPwd: $(P12Password_SDCert)

- task: InstallAppleProvisioningProfile@1
  inputs:
    provProfileSecureFile: 'DressAsistant.mobileprovision'

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, default, specifyPath
    signingOption: 'default' # Options: nosign, default, manual, auto
    useXcpretty: 'false' # Makes it easier to diagnose build failures
